### ISSUE TITLE
fujitsu u7511 i5 1135g7 hackintosh tiger lake issue

### ISSUE THREAD

**Issue by Lutraki** [lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh#12]
Hi,
I followed your guide, but I can't install it on my pc hackintosh
I don't need the IGPU graphics because I do development, but I would like to use this new one for machackintosh too, can you help me?
Do I need to give you something?

Do you have installed the ventura os?
can you give me some tips or suggestions?

follow the specs:
FUJITSU IFEBOOK U7511
Tiger Lake i5-1135G7
Intel xe video
16gb ddr4 ram

Thanks
Luc

**Comment by lshbluesky** [comment]
Since the ACPI contents are different for each laptop model, I cannot guarantee that my laptop's SSDT file will load properly on your laptop.
In particular, SSDT-SPTP.aml patches SPTP Device, an I2C touchpad device unique to Samsung laptops, and will not exist in your laptop's ACPI.

You can use SSDTTime to create an SSDT for your laptop.
https://github.com/corpnewt/SSDTTime
